#import "@/queries/building-blocks/media.gql"
#import "@/queries/building-blocks/link-list.gql"

fragment HeaderFragment on ComponentHeader {
  sys {
    id
  }
  __typename
  headerName
  headerLogo {
    ...MediaFragment
  }
  headerLinkList {
    ...LinkListFragment
  }
}
